/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JFrame;

import Schedule.InterviewSchedule;

/**
 *
 * @author rages
 */
public class SchedulePanelFrame extends javax.swing.JFrame {

    /**
     * Creates new form SchedulePanelFrame
     */       
	String[][] interviews;
    public SchedulePanelFrame() {
    	
    	InterviewSchedule in = new InterviewSchedule();
    	interviews = in.getAllSchedules();
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        schedultTable = new javax.swing.JTable();
        addIntervviewBtn = new javax.swing.JButton();
        updateInterviewBtn = new javax.swing.JButton();
        deleteInterviewBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        interviewId = new javax.swing.JTextField();

        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Schedule Interviews");

        schedultTable.setModel(new javax.swing.table.DefaultTableModel(
           interviews,
            new String [] {
                "Interview ID", "Candidate Id", "Subject", "tech id", "Tech Date", "Tech Time", "Tech rating", "Hr Id", "HR Date", "HR Time", "HR rating", "Result"
            }
        ));
        jScrollPane1.setViewportView(schedultTable);

        addIntervviewBtn.setText("Add Interview");
        addIntervviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIntervviewBtnActionPerformed(evt);
            }
        });

        updateInterviewBtn.setText("Update Interview");
        updateInterviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInterviewBtnActionPerformed(evt);
            }
        });

        deleteInterviewBtn.setText("Delete Interview");
        deleteInterviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInterviewBtnActionPerformed(evt);
            }
        });

        homeBtn.setText("Go Back");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Enter interview ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateInterviewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addIntervviewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteInterviewBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interviewId))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addIntervviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(interviewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(updateInterviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInterviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	AdminPanelFrame adminPanel = new AdminPanelFrame();
    	adminPanel.setVisible(true);
		adminPanel.setExtendedState(JFrame.MAXIMIZED_BOTH);
		dispose();
	}                                      

    private void updateInterviewBtnActionPerformed(java.awt.event.ActionEvent evt) {     
    	UpdateScheduleFrame updateSchedule = new UpdateScheduleFrame(interviewId.getText());
    	updateSchedule.setVisible(true);
		updateSchedule.setExtendedState(JFrame.MAXIMIZED_BOTH);
		dispose();
    }                                                  

    private void deleteInterviewBtnActionPerformed(java.awt.event.ActionEvent evt) {    
    	InterviewSchedule schedule;
		try {
			schedule = new InterviewSchedule("bob123", interviewId.getText());
			if(schedule.delete())
			{
		    	SchedulePanelFrame sPanel = new SchedulePanelFrame();
		    	sPanel.setVisible(true);
				sPanel.setExtendedState(JFrame.MAXIMIZED_BOTH);
				
				dispose();
			}
			else {
				System.out.println("not deleted");
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }                                                  

    private void addIntervviewBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	AddScheduleFrame addSchedule = new AddScheduleFrame();
    	addSchedule.setVisible(true);
		addSchedule.setExtendedState(JFrame.MAXIMIZED_BOTH);
		dispose();
		
    }                                                
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulePanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulePanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulePanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulePanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulePanelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addIntervviewBtn;
    private javax.swing.JButton deleteInterviewBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTextField interviewId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable schedultTable;
    private javax.swing.JButton updateInterviewBtn;
    // End of variables declaration                   
}
