/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JFrame;

import Schedule.InterviewSchedule;
import pojos.HRPanel;
import pojos.TechPanel;
import pojos.User;

/**
 *
 * @author rages
 */
public class UpdateScheduleFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateScheduleFrame 
     * 
     * */
	String techIntName="";
	String hrIntName="";
	UpdateScheduleFrame(){initComponents();}
	InterviewSchedule inter;
	public UpdateScheduleFrame(String interviewId) {
        initComponents();
        messageLabel.setVisible(false);
    	try {
			inter = new InterviewSchedule("bo1006", interviewId);
			candidateName.setText(new User(inter.getCandidateId()).getFirst_name());
			candidateName.setEditable(false);
			candidateId1.setText(inter.getCandidateId());
			candidateId1.setEditable(false);
			subject.setText(inter.getSubject());
			
			
			techDate1.setText(inter.getTechInDate());
			techTime.setText(inter.getTechInTime());
			
			hrDate.setText(inter.getHrInDate());
			hrTime.setText(inter.getHrInTime());
			
			if(inter.getTechId()!=null) {
				techIntName = new TechPanel(inter.getTechId()).getTechName();
				techName.setText(techIntName);
				techName.setEditable(false);
				techId.setText(inter.getTechId());
				techId.setEditable(false);
			}
			if(inter.getHrId()!=null) {
				hrIntName = new HRPanel(inter.getHrId()).getEmpHRName();
				hrName.setText(hrIntName);
				hrName.setEditable(false);
				hrId.setText(inter.getHrId());
				hrId.setEditable(false);
			}
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
    	

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jalaas = new javax.swing.JLabel();
        candidateName = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jalaas1 = new javax.swing.JLabel();
        candidateId1 = new javax.swing.JTextField();
        jalaas2 = new javax.swing.JLabel();
        techId = new javax.swing.JTextField();
        jalaas3 = new javax.swing.JLabel();
        techTime = new javax.swing.JTextField();
        jalaas4 = new javax.swing.JLabel();
        techDate1 = new javax.swing.JTextField();
        jalaas6 = new javax.swing.JLabel();
        techName = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jalaas5 = new javax.swing.JLabel();
        hrDate = new javax.swing.JTextField();
        jalaas7 = new javax.swing.JLabel();
        hrTime = new javax.swing.JTextField();
        jalaas8 = new javax.swing.JLabel();
        hrId = new javax.swing.JTextField();
        jalaas9 = new javax.swing.JLabel();
        hrName = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Update Interview");

        jalaas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas.setText("Candidate Id");

        candidateName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel.setText("Candidate Name");

        subject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jalaas1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas1.setText("Tech Interview Time");

        candidateId1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jalaas2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas2.setText("Subject");

        techId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        techId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techIdActionPerformed(evt);
            }
        });

        jalaas3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas3.setText("Tech Id");

        techTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        techTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techTimeActionPerformed(evt);
            }
        });

        jalaas4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas4.setText("Tech Interview Date");

        techDate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        techDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techDate1ActionPerformed(evt);
            }
        });

        jalaas6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas6.setText("Tech Interviewer Name");

        techName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        techName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techNameActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jalaas5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas5.setText("HR Interview Date");

        hrDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hrDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrDateActionPerformed(evt);
            }
        });

        jalaas7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas7.setText("HR Interview Time");

        hrTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hrTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrTimeActionPerformed(evt);
            }
        });

        jalaas8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas8.setText("HR Id");

        hrId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hrId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrIdActionPerformed(evt);
            }
        });

        jalaas9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jalaas9.setText("HR Interviewer Name");

        hrName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrNameActionPerformed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageLabel.setText("Updated Succesfully");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jalaas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jalaas5, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jalaas7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jalaas9, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hrTime, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hrName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(hrId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jalaas4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jalaas6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(techId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(techDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candidateId1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candidateName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(techTime, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(techName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(522, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidateId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(techId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(techDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(techTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(techName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalaas5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalaas9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLabel))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void techIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_techIdActionPerformed

    private void techTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_techTimeActionPerformed

    private void techDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_techDate1ActionPerformed

    private void techNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_techNameActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
    	
    	Map<String,String> map = new HashMap<>();
    	
    	map.put("CandidateID", candidateId1.getText());
    	map.put("Subject", subject.getText());
    	map.put("TechID", techId.getText());
    	map.put("TechInterviewDate", techDate1.getText());
    	map.put("TechInterviewTime", techTime.getText());
    	map.put("TechRating", null);
    	map.put("empHRID", hrId.getText());
    	map.put("empHRInterviewDate", hrDate.getText());
    	map.put("empHRInterviewTime", hrTime.getText());
    	map.put("empHRRating", null);
    	map.put("Result", null);
    	map.put("ShareResult", null);
    	
    	if(inter.setAllDetails(map))
    	{
    		messageLabel.setVisible(true);
    		
    		try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
    		SchedulePanelFrame sPanel = new SchedulePanelFrame();
        	sPanel.setVisible(true);
    		sPanel.setExtendedState(JFrame.MAXIMIZED_BOTH);
    		dispose();
    	}
    	else {
    		messageLabel.setText("Not updated");
    		messageLabel.setVisible(true);
    	}
    	
    	
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hrDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrDateActionPerformed

    private void hrTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrTimeActionPerformed

    private void hrIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrIdActionPerformed

    private void hrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateScheduleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateScheduleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField candidateId1;
    private javax.swing.JTextField candidateName;
    private javax.swing.JTextField hrDate;
    private javax.swing.JTextField hrId;
    private javax.swing.JTextField hrName;
    private javax.swing.JTextField hrTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jalaas;
    private javax.swing.JLabel jalaas1;
    private javax.swing.JLabel jalaas2;
    private javax.swing.JLabel jalaas3;
    private javax.swing.JLabel jalaas4;
    private javax.swing.JLabel jalaas5;
    private javax.swing.JLabel jalaas6;
    private javax.swing.JLabel jalaas7;
    private javax.swing.JLabel jalaas8;
    private javax.swing.JLabel jalaas9;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField techDate1;
    private javax.swing.JTextField techId;
    private javax.swing.JTextField techName;
    private javax.swing.JTextField techTime;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
