package register;

public class Candidate {
	
	// private String candidateId; - AUTOGENERATED
	private String primarySkills;
	private String secondarySkills;
	private float experience;
	private String qualification;
	private String designation;
	private int noticePeriod;
	private String location;
	private int shareDetails;
	
	public Candidate(String candidateId, String primarySkills, String secondarySkills, float experience,
			String qualification, String designation, int noticePeriod, String location, int shareDetails) {
		super();
		//this.candidateId = candidateId;
		this.primarySkills = primarySkills;
		this.secondarySkills = secondarySkills;
		this.experience = experience;
		this.qualification = qualification;
		this.designation = designation;
		this.noticePeriod = noticePeriod;
		this.location = location;
		this.shareDetails = shareDetails;
	}
	/*
	public void setCandidateId(String candidateId) {
		this.candidateId = candidateId;
	}*/
	public void setPrimarySkills(String primarySkills) {
		this.primarySkills = primarySkills;
	}
	public void setSecondarySkills(String secondarySkills) {
		this.secondarySkills = secondarySkills;
	}
	public void setExperience(float experience) {
		this.experience = experience;
	}
	public void setQualification(String qualification) {
		this.qualification = qualification;
	}
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	public void setNoticePeriod(int noticePeriod) {
		this.noticePeriod = noticePeriod;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public void setShareDetails(int shareDetails) {
		this.shareDetails = shareDetails;
	}

	/*public String getCandidateId() {
		return candidateId;
	}*/

	public String getPrimarySkills() {
		return primarySkills;
	}

	public String getSecondarySkills() {
		return secondarySkills;
	}

	public float getExperience() {
		return experience;
	}

	public String getQualification() {
		return qualification;
	}

	public String getDesignation() {
		return designation;
	}

	public int getNoticePeriod() {
		return noticePeriod;
	}

	public String getLocation() {
		return location;
	}

	public int getShareDetails() {
		return shareDetails;
	}
	
	
}
